services:
  server:
    image: mern-server
    container_name: mern-node-server
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    env_file: ./server/env/development.env
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
    networks:
      - mern-app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - mern-app-network
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   image: myapp-client
  #   container_name: myapp-react-client
  #   command: yarn start
  #   volumes:
  #     - ./client/:/usr/app
  #     - /usr/app/node_modules
  #   depends_on:
  #     - server
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
