FROM node:18-alpine
ENV NODE_ENV=production
# Create App Directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# Install Dependencies
COPY package*.json ./

RUN npm install --omit=dev
# Copy app source code
COPY . .
# Build app
RUN npm run build
# Exports
EXPOSE 8081


CMD ["npm","run", "start"]